import { WorkspaceItem, WorkspaceNodeId } from './types';

export const WORKSPACE_ITEMS: Record<WorkspaceNodeId, WorkspaceItem> = {
  frontend: {
    id: 'frontend',
    title: 'Next.js 15 & React 19 Frontend Layer',
    subtitle: 'Streaming UI & Concurrent Hydration Engine',
    category: 'layer',
    badge: 'CORE ARCHITECTURE',
    icon: '🖥️',
    description:
      'High-performance React 19 client-server boundary leveraging Next.js 15 App Router, React Server Components (RSC), Suspense streaming, and optimistic state transitions.',
    techStack: ['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'Framer Motion'],
    metrics: [
      { label: 'Bundle Impact', value: '42 kB Initial' },
      { label: 'Hydration Target', value: '<120ms TTI' },
      { label: 'Lighthouse Perf', value: '98/100' },
      { label: 'WCAG Compliance', value: 'AA Standard' },
    ],
    color: '#3b82f6',
    emissive: '#1d4ed8',
    position: [0, 0.9, 0],
    targetCamera: [0, 1.8, 3.5],
    details: [
      'Zero-layout-shift UI architecture using container queries and CSS grid',
      'Non-blocking streaming UI with React 19 useActionState and useTransition',
      'Accessible keyboard focus traps and high-contrast ARIA roles',
      'Self-healing error boundaries with retry telemetry',
    ],
    actionLink: '/',
    actionLabel: 'Explore Live Web App',
  },
  'ai-core': {
    id: 'ai-core',
    title: 'AI / LLM Neural Inference Engine',
    subtitle: 'Multi-Turn Streaming & Structured Generative UI',
    category: 'layer',
    badge: 'INTELLIGENCE CORE',
    icon: '🧠',
    description:
      'Orchestrates real-time LLM inference pipelines with token-by-token Server-Sent Events (SSE), typed Zod tool invocations, and adaptive prompt engineering.',
    techStack: ['Vercel AI SDK', 'Claude 3.5 Sonnet', 'Gemini 1.5 Pro', 'Zod Schemas', 'SSE'],
    metrics: [
      { label: 'First Token Latency', value: '<320ms TTFT' },
      { label: 'Tool Validation', value: '100% Type-Safe' },
      { label: 'Stream Reliability', value: '99.98% Pass' },
      { label: 'Token Efficiency', value: '~45 tps' },
    ],
    color: '#8b5cf6',
    emissive: '#6d28d9',
    position: [1.8, 1.2, -0.4],
    targetCamera: [2.2, 1.8, 2.0],
    details: [
      'Server-side tool calling with scoreCandidate Zod verification',
      'Resilient backoff retry algorithm for rate limits (429) and network drops',
      'Simulated SSE mock fixture pipeline for 100% offline-capable CI test suites',
      'Generative UI component mapper translating JSON tool states into interactive cards',
    ],
    actionLink: '/interview',
    actionLabel: 'Launch AI Interview',
  },
  backend: {
    id: 'backend',
    title: 'Node.js & Edge API Gateway',
    subtitle: 'Serverless Edge Functions & Security Perimeter',
    category: 'layer',
    badge: 'API GATEWAY',
    icon: '⚡',
    description:
      'High-throughput Edge API runtime handling authentication validation, payload schema guards, and upstream microservice orchestration.',
    techStack: ['Node.js LTS', 'Next.js Edge Runtime', 'Zod', 'REST APIs', 'Firebase Admin'],
    metrics: [
      { label: 'Edge Cold Start', value: '<45ms' },
      { label: 'API Security', value: 'Zero-Secret Leak' },
      { label: 'Schema Overhead', value: '<2ms Guard' },
      { label: 'Concurrency', value: 'Global Edge' },
    ],
    color: '#10b981',
    emissive: '#047857',
    position: [-1.8, 1.2, -0.4],
    targetCamera: [-2.2, 1.8, 2.0],
    details: [
      'Encrypted server-only environment variable encapsulation (no leaked client keys)',
      'Stateless request verification with automatic rate-limit headers',
      'OMDb movie ingestion engine and candidate telemetry endpoints',
      'Health diagnostic telemetry route with real-time status reporting',
    ],
    actionLink: '/health',
    actionLabel: 'View System Diagnostics',
  },
  database: {
    id: 'database',
    title: 'Vector Memory & Cloud Data Store',
    subtitle: 'Realtime Sync & Distributed State Store',
    category: 'layer',
    badge: 'DATA LAYER',
    icon: '💾',
    description:
      'Hybrid data persistence architecture combining Firebase Realtime Database cloud synchronization with local storage fallback layers.',
    techStack: ['Firebase Realtime DB', 'Firebase Auth', 'Local Storage Fallback', 'Vector Embeddings'],
    metrics: [
      { label: 'Cloud Sync Latency', value: '<65ms' },
      { label: 'Offline Fallback', value: '100% Zero Crash' },
      { label: 'Session Integrity', value: 'Encrypted JWT' },
      { label: 'Storage Footprint', value: 'Optimized JSON' },
    ],
    color: '#f59e0b',
    emissive: '#b45309',
    position: [0, 0.4, -1.6],
    targetCamera: [0, 1.5, -0.2],
    details: [
      'Seamless transition from cloud Firebase to localStorage when offline or unauthenticated',
      'Atomic user watchlist updates with optimistic client-side synchronization',
      'Zero credential exposure on client bundle with automatic configuration fallbacks',
      'Realtime subscriptions for cross-tab user session updates',
    ],
    actionLink: '/favourites',
    actionLabel: 'Open Watchlist Store',
  },
  hirevium: {
    id: 'hirevium',
    title: 'HIREVIUM — AI Hiring Intelligence OS',
    subtitle: 'Multi-Turn Technical Interview & Generative Assessment',
    category: 'project',
    badge: 'FLAGSHIP CAPSTONE',
    icon: '🎯',
    description:
      'Production-grade streaming AI qualification interview platform with server-side candidate evaluation tools, typed tool states, and intentional motion feedback.',
    techStack: ['React 19', 'AI SDK', 'Zod Tool Calling', 'Motion with Intent', 'Vitest & RTL'],
    metrics: [
      { label: 'Evaluation Depth', value: '5 Competency Axes' },
      { label: 'Stream Speed', value: 'Realtime SSE' },
      { label: 'Test Coverage', value: '18 Unit + E2E' },
      { label: 'Motion States', value: '6 Lifecycle Phases' },
    ],
    color: '#06b6d4',
    emissive: '#0e7490',
    position: [-1.4, 0.85, 1.1],
    targetCamera: [-1.6, 1.4, 2.5],
    details: [
      'Interactive multi-turn technical interview chat with auto-scroll and jump-to-latest UX',
      'Server-side scoreCandidate AI tool rendering structured candidate scorecards',
      'Failure resilience system with rate-limit countdowns and manual retry triggers',
      'AIActionButton with micro-animations communicating send, loading, success, and error',
    ],
    actionLink: '/interview',
    actionLabel: 'Launch HIREVIUM Chat',
  },
  indra: {
    id: 'indra',
    title: 'INDRA AI — Multimodal Agent System',
    subtitle: 'Autonomous Vision & Multi-Step Reasoning Engine',
    category: 'project',
    badge: 'AGENT PLATFORM',
    icon: '🤖',
    description:
      'Multimodal AI agent system capable of parsing technical UI layouts, performing visual regression inspection, and generating structured engineering action plans.',
    techStack: ['Gemini 1.5 Pro', 'Vision Transformers', 'LangChain', 'FastAPI', 'Next.js'],
    metrics: [
      { label: 'Vision Accuracy', value: '99.2%' },
      { label: 'Reasoning Depth', value: 'Multi-Step CoT' },
      { label: 'Execution Engine', value: 'Agentic Loop' },
      { label: 'Response Latency', value: '<480ms' },
    ],
    color: '#ec4899',
    emissive: '#be185d',
    position: [1.4, 0.85, 1.1],
    targetCamera: [1.6, 1.4, 2.5],
    details: [
      'Automated visual element localization and UI defect identification',
      'Chain-of-thought structured reasoning outputting JSON schema patches',
      'Context-aware memory buffer preserving multi-step developer conversations',
      'Exportable design audit checklists and accessibility remediation blueprints',
    ],
    actionLink: '/playground/buttons',
    actionLabel: 'Explore Interactive Lab',
  },
  stackscout: {
    id: 'stackscout',
    title: 'StackScout — AI Code Evaluation Engine',
    subtitle: 'Automated Codebase Diagnostics & Linting Assistant',
    category: 'project',
    badge: 'DEVELOPER TOOLING',
    icon: '🔍',
    description:
      'Intelligent developer productivity suite that analyzes repository structures, tests edge-case resilience, and generates automated test fixtures for modern web stacks.',
    techStack: ['Vitest', 'Playwright', 'Oxc AST Parser', 'TypeScript AST', 'GitHub Actions'],
    metrics: [
      { label: 'Analysis Speed', value: '150k lines/s' },
      { label: 'False Positive', value: '<0.5%' },
      { label: 'Rule Coverage', value: '45+ Standards' },
      { label: 'CI Execution', value: '<45s Full Run' },
    ],
    color: '#eab308',
    emissive: '#a16207',
    position: [-2.2, 0.5, 0.2],
    targetCamera: [-2.5, 1.2, 1.8],
    details: [
      'Automated Vitest test suite generator for React 19 and React Testing Library',
      'Zero-flakiness Playwright end-to-end test execution with network mocking',
      'Accessibility audit engine checking ARIA roles, color contrast, and keyboard tab flow',
      'Continuous Integration pipeline configured with GitHub Actions workflow automation',
    ],
    actionLink: '/playground',
    actionLabel: 'Open Component Playground',
  },
  cinetrack: {
    id: 'cinetrack',
    title: 'CineTrack — Media Discovery Intelligence',
    subtitle: 'Movie Discovery & Realtime Watchlist Catalog',
    category: 'project',
    badge: 'MEDIA ENGINE',
    icon: '🎬',
    description:
      'Full-stack cinema intelligence and personalized catalog platform connecting OMDb API metadata with Firebase cloud sync and offline local persistence.',
    techStack: ['Next.js 15', 'OMDb API', 'Firebase RTDB', 'Local Fallbacks', 'Tailwind v4'],
    metrics: [
      { label: 'Catalog Index', value: '1M+ Titles' },
      { label: 'Query Cache', value: '300s TTL' },
      { label: 'Search Speed', value: '<180ms' },
      { label: 'Favorites Sync', value: 'Instant Multi-Tab' },
    ],
    color: '#0284c7',
    emissive: '#0369a1',
    position: [2.2, 0.5, 0.2],
    targetCamera: [2.5, 1.2, 1.8],
    details: [
      'Instant search with dynamic pill filters for Movies, Series, and Episodes',
      'Rich detail pages with Rotten Tomatoes, IMDb, and Metacritic critic aggregate ratings',
      'Cloud synchronized watchlist with realtime counter badge in header navigation',
      'Strict MVVM architecture separating validation models, view models, and UI views',
    ],
    actionLink: '/',
    actionLabel: 'Launch CineTrack',
  },
};

export const WORKSPACE_ITEM_LIST: WorkspaceItem[] = Object.values(WORKSPACE_ITEMS);
